[package]
name = "gyat"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
rare = { git = "https://github.com/nguyenhuy0905/rare" }
flate2 = "1.0.35"
hex = "0.4.3"
sha1 = "0.10.6"
